version: 2
jobs:
  build:
    verify:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: bash ./scripts/verify.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

  deploy-docker-image:
    docker:
      - image: ubuntu:14.04

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master
