version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: bash ./scripts/verify.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy-docker-image:
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "63:40:cf:2b:98:fb:f5:a1:5a:65:de:29:12:fa:c2:b2"
      - run:
          command: |
            ssh ${WEB_SERVER}
            echo 'successfully logged in'


workflows:
  build-deploy:
    jobs:
      - build
      - deploy-docker-image:
          requires:
            - build
          filters:
            branches:
              only: master
