version: '3.7'
services:
  portfolio:
    build: .
    volumes:
      - certbot-etc:/usr/src/app/letsencrypt
    networks:
      - app
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - portfolio
    volumes:
      - ./nginx/prod/conf.d:/etc/nginx/conf.d"
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app
  certbot:
    image: certbot/dns-digitalocean
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./digitalocean.ini:./
    command: >
        certonly
            --agree-tos
            --dns-digitalocean
            --dns-digitalocean-credentials digitalocean.ini
            -d *.kirbyjs.com
            -d kirbyjs.com
            --preferred-challenges dns-01
            --server https://acme-v02.api.letsencrypt.org/directory

volumes:
  certbot-etc:
  certbot-var:

networks:
  app:
