name: portfolio
on: [ push ]
jobs:
  create_infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hashicorp/terraform-github-actions/init@v0.4.6
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./tf
      - uses: hashicorp/terraform-github-actions/validate@v0.4.6
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./tf
      - uses: hashicorp/terraform-github-actions/apply@v0.4.6
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: ./tf
  build_and_deploy:
    needs: create_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get_node_js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm_build
        run: |
          npm ci
          npm run build
        env:
          CI: true
      - name: add_aws_cli
        uses: docker://infrastructureascode/aws-cli
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cp -r ./assets/public/* ./assets/bundle
          aws s3 cp ./assets/bundle s3://kirbyjs.com/ --recursive
          aws s3 cp ./assets/bundle/index.html s3://kirbyjs.com/ --cache-control max-age=0
