name: deploy
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir $HOME/.ssh && ssh-keyscan -t rsa $host >> $HOME/.ssh/known_hosts
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          mv ./id_rsa $HOME/.ssh/deploy_key

          chmod 700 "$HOME/.ssh"
          chmod 600 "$HOME/.ssh/known_hosts"
          chmod 600 "$HOME/.ssh/deploy_key"

          eval $(ssh-agent)
          ssh-add "$HOME/.ssh/deploy_key"
          ssh -o StrictHostKeyChecking=no -A -tt $username@$host whoami
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
