name: kirbyjs
on:
  push:
    branches:
      - master
jobs:
  create_infra:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.14.4
    steps:
      - uses: actions/checkout@v1
      - name: create_infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./tf
          terraform init
          terraform validate
          terraform destory -auto-approve
